<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><title>SoR</title>{!! HTML::style('css/bootstrap.min.css') !!}
{!! HTML::style('css/stylesheet.css') !!}
{!! HTML::style('https://fonts.googleapis.com/css?family=Raleway:400,300,500,700') !!}
{!! HTML::style('https://fonts.googleapis.com/css?family=Roboto') !!}  
{!! HTML::style('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css') !!}
{!! HTML::style('css/jquery-ui.structure.min.css') !!}
{!! HTML::style('css/jquery-ui.min.css') !!}
{!! HTML::style('css/jquery-ui.theme.min.css') !!}
{!! HTML::script("https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js") !!}
{!! HTML::script('js/userHeaderAjax.js') !!}
{!! HTML::script('js/jquery-ui.min.js') !!}</head><body><div class="container-fluid top-side"><div class="row"><div class="col-md-8 col-sm-8 col-xs-6"><h1 class="logo"><a href="{{url('home')}}"><img src="images/logo.png" alt="sor"></a><span>Social Recommender</span></h1></div><div class="col-md-4 col-sm-4 col-xs-6"><div class="user-box"><img src="images/avatar.jpg" alt="avatar"><p class="name"> 
<?php echo Auth::user()->name ?></p><ul class="usermenu"><li><a href="{{url('profile')}}"> <span class="glyphicon glyphicon-user"> </span>Profile</a></li><li><a href="{{url('auth/logout')}}"> <span class="glyphicon glyphicon-log-out"> </span>Logout</a></li></ul></div></div></div></div></body></html><div class="container-fluid main"><div class="row row-eq-height"><div class="col-md-2 col-sm-12 sidebar"><ul><li><span class="glyphicon glyphicon-search"></span><a href="{{url('home')}}">Search</a></li><li><span class="glyphicon glyphicon-list-alt"></span><a href="javascript:void(0)">Search History</a></li><li><span class="glyphicon glyphicon-star"></span><a href="javascript:void(0)">Favorites</a></li><li><span class="glyphicon glyphicon-unchecked"></span><a href="graph.html">Graph</a></li><li><span class="glyphicon glyphicon-file"></span><a href="report.html">Report</a></li></ul></div><div class="col-md-7 col-sm-6 application"><div class="results"><p class="resultHeader">There are <span class="resultNo">3 </span>results based on your query.</p><div class="row allResults"></div></div></div><div class="col-md-3 col-sm-6 searchBar"><img src="images/hex-loader2.gif" alt="loading.." class="loader"><div id="accordion" class="panel-group hidden"><div class="panel panel-default"><div class="panel-heading"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#searchPerson">Search People</a></h4></div><div id="searchPerson" class="panel-collapse collapse"><div class="panel-body">{!! Form::open(array('url' => 'person', 'id' => 'personSearchForm', 'class' => 'search-form', 'role' => 'form')) !!}<div class="row"><div class="col-md-12">{!! Form::Label('Name','Name') !!}</div><div class="col-md-12"><div class="form-group">{!! Form::text('personName', null, ['class' => 'input  form-control', 'placeholder' => 'name..']) !!}</div></div><div class="col-md-12">{!! Form::Label('profession','Profession') !!}</div><div class="col-md-12"><div class="form-group">{!! Form::text('personProfession', null, ['class' => 'input  form-control', 'placeholder' => 'profession..']) !!}</div></div><div class="col-md-12">{!! Form::Label('nationality','Nationality') !!}</div><div class="col-md-12"><div class="form-group">{!! Form::text('personCountry', null, ['class' => 'input  form-control', 'placeholder' => 'country..']) !!}</div></div><div class="col-md-12 text-right">{!! Form::submit('Search',  ['class' => 'btn']) !!}</div></div>{!! Form::close() !!}</div></div></div><div class="panel panel-default"><div class="panel-heading"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#searchEvent">Search Events</a></h4></div><div id="searchEvent" class="panel-collapse collapse"><div class="panel-body">{!! Form::open(array('url' => 'event', 'id' => 'personSearchForm', 'class' => 'search-form', 'role' => 'form')) !!}<div class="row"><div class="col-md-12">{!! Form::Label('eventName','Event name') !!}<div class="form-group"> 
{!! Form::text('name', null, ['class' => 'input form-control', 'placeholder' => 'name..']) !!}                    </div></div><div class="col-md-12">{!! Form::Label('eventType','Event Type') !!}<div class="form-group"> 
{!! Form::text('eventTypeUri', null, ['class' => 'input form-control', 'placeholder' => 'type..']) !!}</div></div><div class="col-md-12">{!! Form::Label('locationUri','Event Location') !!}<div class="form-group"> 
{!! Form::text('locationUri', null, ['class' => 'input form-control', 'placeholder' => 'location..']) !!}</div></div><div class="col-md-12">                    
{!! Form::Label('startDate','Start date') !!}                 </div><div class="col-md-6 col-sm-6 col-xs-6"><div class="form-group">{!! Form::text('startDateMin', null, ['class' => 'input form-control', 'id' => 'eventStartDateMin', 'placeholder' => 'minimum..']) !!}          </div></div><div class="col-md-6 col-sm-6 col-xs-6">            <div class="form-group">{!! Form::text('startDateMax', null, ['class' => 'input form-control', 'id' => 'eventStartDateMax', 'placeholder' => 'maximum..']) !!}</div></div><div class="col-md-12">{!! Form::Label('endDate','End date') !!}                            </div><div class="col-md-6 col-sm-6 col-xs-6">                        <div class="form-group">{!! Form::text('endDateMin', null, ['class' => 'input form-control', 'id' => 'eventEndDateMax', 'placeholder' => 'minimum..']) !!}</div></div><div class="col-md-6 col-sm-6 col-xs-6"> <div class="form-group"> 
{!! Form::text('endDateMax', null, ['class' => 'input form-control', 'id' => 'eventEndDateMax', 'placeholder' => 'maximum..']) !!}</div></div><div class="col-md-12 text-right">{!! Form::submit('Search',  ['class' => 'btn']) !!}</div></div>{!! Form::close() !!}</div></div></div><div class="panel panel-default"><div class="panel-heading"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#searchBook">Search Books</a></h4></div><div id="searchBook" class="panel-collapse collapse"><div class="panel-body">{!! Form::open(array('url' => 'book', 'id' => 'bookSearchForm', 'class' => 'search-form', 'role' => 'form')) !!}<div class="row"><div class="col-md-12">{!! Form::Label('bookTitle','Book title') !!}<div class="form-group">{!! Form::text('name', null, ['class' => 'input form-control', 'placeholder' => 'title..']) !!}</div></div><div class="col-md-12">{!! Form::Label('author','Author') !!}<div class="form-group">{!! Form::text('authorUri', null, ['class' => 'input form-control', 'placeholder' => 'name..']) !!}</div></div><div class="col-md-12">{!! Form::Label('illustrator','Illustrator') !!}<div class="form-group"> 
{!! Form::text('illustratorUri', null, ['class' => 'input form-control', 'placeholder' => 'name..']) !!}</div></div><div class="col-md-12"> 
{!! Form::Label('literaryGenre','Literary Genre') !!}<div class="form-group"> 
{!! Form::text('literaryGenreUri', null, ['class' => 'input form-control', 'placeholder' => 'genre..']) !!}</div></div><div class="col-md-12">{!! Form::Label('Number of Pages') !!}</div><div class="col-md-6 col-sm-6 col-xs-6"><div class="form-group">{!! Form::text('numberOfPagesMin', null, ['class' => 'input form-control', 'placeholder' => 'minimum..']) !!}</div></div><div class="col-md-6 col-sm-6 col-xs-6"><div class="form-group">{!! Form::text('numberOfPagesMax', null, ['class' => 'input form-control', 'placeholder' => 'maximum..']) !!}</div></div><div class="col-md-12">{!! Form::label('numberOfVolumes','Number of Volumes') !!}<div class="form-group">{!! Form::text('numberOfVolumes', null, ['class' => 'input form-control', 'placeholder' => 'number of volumes..']) !!}	</div></div><div class="col-md-12 text-right">{!! Form::submit('Search',  ['class' => 'btn']) !!}</div></div>{!! Form::close() !!}</div></div></div><div class="panel panel-default"><div class="panel-heading"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#searchPlace">Search Places</a></h4></div><div id="searchPlace" class="panel-collapse collapse"><div class="panel-body">{!! Form::open(array('url' => 'place', 'id'=>'placeSearchForm', 'class' => 'search-form', 'role' => 'form')) !!}<div class="row"><div class="col-md-12">{!! Form::Label('placeName','Place name') !!}<div class="form-group">{!! Form::text('name', null, ['class' => 'input form-control', 'placeholder' => ' name..']) !!}</div></div><div class="col-md-12"> 
{!! Form::Label('placeType','Place Type') !!}<div class="form-group"> 
{!! Form::text('placeTypeUri', null, ['class' => 'input form-control', 'placeholder' => 'type..']) !!}</div></div><div class="col-md-12">{!! Form::Label('country','Country') !!}<div class="form-group">{!! Form::text('countryUri', null, ['class' => 'input form-control', 'placeholder' => 'country..']) !!}</div></div><div class="col-md-12 text-right">{!! Form::submit('Search',  ['class' => 'btn']) !!}</div></div>{!! Form::close() !!}</div></div></div><div class="panel panel-default"><div class="panel-heading"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#searchInstitute">Search Educational Institutions</a></h4></div><div id="searchInstitute" class="panel-collapse collapse"><div class="panel-body">{!! Form::open(array('url' => 'institute', 'class' => 'search-form', 'role' => 'form')) !!}<div class="row"><div class="col-md-12">{!! Form::Label('instituteName','Institute name') !!}<div class="form-group"> 
{!! Form::text('name', null, ['class' => 'input form-control', 'placeholder' => 'name..']) !!}</div></div><div class="col-md-12">{!! Form::Label('educationalInstituteType','Educational Institute Type') !!}<div class="form-group">{!! Form::text('eduTypeUri', null, ['class' => 'input form-control', 'placeholder' => 'type..']) !!}</div></div><div class="col-md-12">{!! Form::Label('location','Location') !!}<div class="form-group">{!! Form::text('locationUri', null, ['class' => 'input form-control', 'placeholder' => 'location..']) !!}</div></div><div class="col-md-12">{!! Form::Label('country','Country') !!}<div class="form-group">{!! Form::text('countryUri', null, ['class' => 'input form-control', 'placeholder' => 'country..']) !!}</div></div><div class="col-md-12">{!! Form::Label('principal','Principal') !!}<div class="form-group">{!! Form::text('principalUri', null, ['class' => 'input form-control', 'placeholder' => 'name..']) !!}</div></div><div class="col-md-12">{!! Form::Label('rector','Rector') !!}<div class="form-group">{!! Form::text('rectorUri', null, ['class' => 'input form-control', 'placeholder' => 'name..']) !!}</div></div><div class="col-md-12">                
{!! Form::Label('numberOFAcademicStaff','Number of Academic staff:') !!}</div><div class="col-md-6 col-sm-6 col-xs-6"><div class="form-group">{!! Form::text('nrOfAcademicStaffMin', null, ['class' => 'input form-control', 'placeholder' => 'minimum..']) !!}</div></div><div class="col-md-6 col-sm-6 col-xs-6"><div class="form-group">{!! Form::text('nrOfAcademicStaffMax', null, ['class' => 'input form-control', 'placeholder' => 'maximum..']) !!}</div></div><div class="col-md-12">            
{!! Form::label('numberOFStudents','Number of Students:') !!}</div><div class="col-md-6 col-sm-6 col-xs-6"><div class="form-group"> 
{!! Form::text('nrOfStudentsMin', null, ['class' => 'input form-control', 'placeholder' => 'minimum..']) !!}</div></div><div class="col-md-6 col-sm-6 col-xs-6"><div class="form-group">{!! Form::text('nrOfStudentsMax', null, ['class' => 'input form-control', 'placeholder' => 'maximum..']) !!}</div></div><div class="col-md-12 text-right">{!! Form::submit('Search',  ['class' => 'btn']) !!}</div></div>{!! Form::close() !!}</div></div></div></div></div></div></div>{!! HTML::script('js/searches.js') !!}<footer class="container-fluid footer-side"><div class="row"><div class="col-md-12"><p>This is the footer. Information soon to be added here</p></div></div></footer>{!! HTML::script('js/bootstrap.min.js')  !!}